services:
  backend:
    build: ./trivia_backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build: ./TriviaFrontend
    container_name: frontend
    ports:
      - "4300:8080"
    depends_on:
      - backend

